FROM eclipse-temurin:17-jre

# Создать директорию для данных
RUN mkdir -p /app/data

# Рабочая директория
WORKDIR /app

# Скопировать target в /app
COPY target/*.jar .

# Посмотреть что скопировано
RUN ls -la /app && sleep 1

# Открываем порт
EXPOSE 8010

# Команда запуска
CMD ["java", "-jar", "squeeze-alice-1.0.jar"]
