#!/usr/bin/env bash
# sudo chmod +x *.sh
BGreen='\033[1;32m'
NC='\033[0m' # No Color
echo -e ${BGreen}"START"${NC}

file_name=$(basename "$0" .sh)
remote="${file_name##*_}" 
echo -e ${BGreen}"IP: $remote"${NC}
#remote=192.168.1.123

#rm -r target
#mvn package
ssh root@$remote "mkdir -p /opt/squeeze-alice-1.0"
echo -e ${BGreen}"COPY target TO /opt/squeeze-alice-1.0/"${NC}
#sshpass -p "12345" scp -r target root@$remote:/opt/squeeze-alice-1.0/
sshpass -p "12345" rsync -avh --progress target/ root@$remote:/opt/squeeze-alice-1.0/


echo -e ${BGreen}"COPY squeeze-alice.service TO /lib/systemd/system/"${NC}
#sshpass -p "12345" scp utils/squeeze-alice.service root@$remote:/lib/systemd/system/
sshpass -p "12345" rsync -avh --progress utils/squeeze-alice.service root@$remote:/lib/systemd/system/

echo -e ${BGreen}"SYSTEMCTL ENABLE, RELOAD, RESTART"${NC}
ssh root@$remote sudo systemctl enable squeeze-alice.service
ssh root@$remote sudo systemctl daemon-reload
ssh root@$remote sudo systemctl restart squeeze-alice.service

echo -e ${BGreen}"FINISH"${NC}

sleep 15
#$SHELL
