#!/usr/bin/env bash
# sudo chmod +x *.sh
BGreen='\033[1;32m'
NC='\033[0m' # No Color
echo -e ${BGreen}"START"${NC}

file_name=$(basename "$0" .sh)
remote="${file_name##*_}" 
echo -e ${BGreen}"IP: $remote"${NC}
#remote=192.168.1.123

echo -e ${BGreen}"DEL /opt/squeeze-alice-1.0/"${NC}
ssh root@$remote sudo rm -r /opt/squeeze-alice-1.0

echo -e ${BGreen}"DEL /lib/systemd/system/squeeze-alice.service"${NC}
ssh root@$remote sudo rm /lib/systemd/system/squeeze-alice.service

echo -e ${BGreen}"SYSTEMCTL STOP DISABLE, RELOAD"${NC}
ssh root@$remote sudo systemctl stop squeeze-alice.service
ssh root@$remote sudo systemctl disable squeeze-alice.service
ssh root@$remote sudo systemctl daemon-reload

echo -e ${BGreen}"FINISH"${NC}


sleep 15
#$SHELL
