#!/usr/bin/env bash
# sudo chmod +x *.sh
BGreen='\033[1;32m'
NC='\033[0m' # No Color
echo -e ${BGreen}"START"${NC}

file_name=$(basename "$0" .sh)
remote="${file_name##*_}" 
echo -e ${BGreen}"IP: $remote"${NC}
#remote=192.168.1.123

echo -e ${BGreen}"DEL /opt/squeeze-alice-1.0/"${NC}
ssh root@$remote rm -r /opt/squeeze-alice-1.0

echo -e ${BGreen}"DEL /lib/systemd/system/squeeze-alice.service"${NC}
ssh root@$remote rm /lib/systemd/system/squeeze-alice.service

echo -e ${BGreen}"SYSTEMCTL STOP DISABLE, RELOAD"${NC}
#ssh root@$remote systemctl stop squeeze-alice.service
#ssh root@$remote systemctl disable squeeze-alice.service
#ssh root@$remote systemctl daemon-reload
ssh root@$remote systemctl status squeeze-alice.service

echo -e ${BGreen}"LS OPT"${NC}
ssh root@$remote ls /opt/
ssh root@$remote ls -l /opt/
ssh root@$remote ls -l /opt/ 2>&1
echo -e ${BGreen}"LS ~"${NC}
ssh root@$remote ls -l ~/
ssh root@$remote ls -l ~/ 2>&1

ssh root@$remote ls ~/

#echo -e ${BGreen}"LS OPT"${NC}
#ssh root@$remote ls /opt/ 2>&1
#echo -e ${BGreen}"LS ~"${NC}
#ssh root@$remote ls ~/ 2>&1
#
#
#echo -e ${BGreen}"LS OPT -t"${NC}
#ssh -t root@$remote sudo ls /opt/
#
#echo -e ${BGreen}"LS ~ -t"${NC}
#ssh -t root@$remote sudo ls ~/

echo -e ${BGreen}"FINISH"${NC}


#sleep 15
$SHELL
