#!/usr/bin/env bash
# sudo chmod +x *.sh
BGreen='\033[1;32m'
NC='\033[0m' # No Color

export JAVA_HOME=~/.jdks/corretto-18.0.2
export PATH=$JAVA_HOME/bin:$PATH

echo -e "\n"${BGreen}"MVN PACKAGE"${NC}"\n"
printf '%s\n' "DIR: ${PWD##*/}"
rm -r target
mvn package
#cp *.json target
mv target/*.jar target/app.jar
echo -e "\n"${BGreen}"FINISH MVN"${NC}"\n"

# Соберите образ локально


# Активируйте multi-arch сборку
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --use --name multiarch --platform linux/amd64,linux/arm/v7

# Соберите и сразу загрузите образ
docker buildx build \
  --platform linux/arm/v7 \
  -f dockerfile_arm \
  -t knovash/squeeze-alice-local-arm:latest \
  --push .  # Автоматическая загрузка в Docker Hub

echo -e "\n${BGreen}BUILD & PUSH COMPLETE${NC}\n"




#sleep 5
$SHELL
