#!/usr/bin/env bash
# sudo chmod +x *.sh
BGreen='\033[1;32m'
NC='\033[0m' # No Color
echo -e ${BGreen}"START"${NC}

sudo mkdir -p /opt/squeeze-alice-1.0
echo -e ${BGreen}"COPY target TO /opt/squeeze-alice-1.0/"${NC}
sudo cp -r target /opt/squeeze-alice-1.0/

echo -e ${BGreen}"COPY squeeze-alice.service TO /lib/systemd/system/"${NC}
sudo cp utils/squeeze-alice.service /lib/systemd/system/

echo -e ${BGreen}"SYSTEMCTL ENABLE, RELOAD, RESTART"${NC}
sudo systemctl enable squeeze-alice.service
sudo systemctl daemon-reload
sudo systemctl restart squeeze-alice.service

echo -e ${BGreen}"FINISH"${NC}
