[DEFAULT]

# URL сервера Squeeze-Alice
SPEAK_URL = http://192.168.1.130:8010/cmd

# Имя устройства ввода для поиска
DEVICE_NAME = HAOBO Technology USB Composite Device Keyboard

# Код клавиши (EV_KEY) для кнопки микрофона
EVENT_CODE = 582

# Длительность записи в секундах
RECORD_SECONDS = 4

# Включать звуковой сигнал до и после записи (true/false)
ENABLE_START_BEEP = true

# Пауза после сигнала перед началом записи (сек)
START_DELAY = 1

# Ключи Yandex SpeechKit
YANDEX_API_KEY = AQVN3dKzcyDkaTa9JPJ5Y4q9PXiRCIDaDuGPa3w2
YANDEX_FOLDER_ID = ajetqapn6874d4rbq97i

SIGNAL_PLAYER = btremote
SIGNAL_VALUE = beep2
